---
title: "LAB 5"
author: "DATA ME PLS"
date: "February 13, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

milk <- read.csv('state_milk_production.csv')
head(milk)
```
MAKE SURE TO RUN THE CODE ABOVE SO YOU CAN GET THE DATA!!!!


# MILK IS GOOD EVEN THOUGH WE BECOME LACTOSE INTOLERANT OVER TIME
The year when the most milk was produced in the United States.
The year when the least milk was produced in the United States.
In 2017, report the 5 states that produced the most milk. (Hint: Use arrange)
In 2017, report the 5 states that produced the least milk. (Hint: Use arrange)

## Group SHit
milksub <- milk %>%
  filter(state %in% c('Colorado','California','Wisconsin','Georgia', 'Alaska')) %>%
  select(state, year, milk_million)

ggplot(data = milksub, aes(x = year, y = milk_million, color = state)) +
  geom_point() + 
  ggtitle('Pounds of milk over time by state') +
  xlab('Year') +
  ylab('Milk Produced (Million lb)')
  
milk_now <- milk %>%
  filter(year == 2017) %>%
  arrange (desc(milk_produced)) 
  
largest_state2 <- milk %>%
  group_by(year) %>%
  summarize(sum_milk = sum(milk_million))%>%
  arrange(desc(sum_milk))

## 1997 (James)

## 1998 (Chris)

## 1999 (Anna)
bday_milk <- milk %>%
  filter(year == 1999) %>%
  summarise(mmean = mean(milk_produced/1000000),
            mmedian = median (milk_produced/1000000))

bday_state <- milk %>%
  filter(year == 1999) %>%
  arrange(desc(milk_produced))