---
title: "Lab 7"
author: "Data Me Pls: Chris, James, Amanda, Anna"
date: "February 22, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, eval=FALSE}
## RUN THIS CODE TO GET THE DATA! (WE CAN TIDY LATER)
library(tidyverse)
housepwr <- read.table(unz("household_power_consumption.zip", "household_power_consumption.txt"),
                        sep= ";", header= T, na.strings = c("NA","","?"), stringsAsFactors = FALSE)
na.omit(housepwr)
 
```
str
# Findings

# Dataset Description



---

## Amanda

How does energy consumption in the kitchen change across months?
How does the proportion of each type of energy consumption change across months?

How do i address question

-graph
-summary statistic


## James

## Chris

How does average global active power change every month throughout the four years? 

```{r, eval=FALSE}
householdpwr<-housepwr %>% 
  separate(Date, into = c("Day","Month","Year"), sep = "/", convert = TRUE) %>%
  select(Day,Month,Year,Global_active_power)

householdpwr2 <- householdpwr %>%
  group_by(Year, Month) %>%
  summarize(mean_pwr = mean(Global_active_power, na.rm = TRUE) , count = n())

```
## Anna