---
title: "Lab 8"
author: "Data Me Pls: James, Chris, Amanda, Anna"
date: "March 1, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
install.packages("readxl")
library(readxl)
suicides <- read.table(file= "master.xls", sep= "\t", header= TRUE, na.strings=c("NA", "", "?"))

```
# QUESTION
Dataset: https://www.kaggle.com/russellyates88/suicide-rates-overview-1985-to-2016

###Why important

###Overall Summary

###Reconmendatioins

---

### Chris (GDP, #)

### Amanda (Gender, #)
```{r setup, include=FALSE}
library(tidyverse)
#View(suicides)
suicides <- read.table(file= "master.xls", sep= "\t", header= TRUE, na.strings=c("NA", "", "?", 0))
suicideByGender <- select(suicides, sex, suicides_no, country) %>% drop_na()
#View(suicideByGender)

ggplot(data=suicideByGender, aes(x=sex, y=suicides_no, fill=sex)) + geom_col() + labs(x="Gender", y="Number Of Suicides", title = "Number of Suicides by Country and Gender", legend = "Gender") + theme(legend.position = "none")


```

### James (Who knows)

### Anna (Generation/Age, #)
```{r, echo= FALSE}
agecount <- suicides %>%
  select("age", "suicides_no", "generation")

generationtotal <- agecount %>%
  group_by(generation) %>%
  summarise(total= sum(suicides_no))

agetotal <- agecount %>%
  group_by(age) %>%
  summarise(total=sum(suicides_no))
```
