---
title: "Lab 13"
author: "Data Me Pls: Amanda, James, Chris, Anna"
date: "April 12, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


## Amanda

## James

## Chris

## Anna

__Question:__ Is there a correlation between Life Expectancy and Population Size?
```{r, Eval=FALSE}
library(tidyverse)
library(gapminder)

gapminder <- gapminder

pop_size <- gapminder%>%
  select(pop)

life_exp <- gapminder %>%
  select(lifeExp)

life_exp <- life_exp$lifeExp
pop_size <- pop_size$pop

real_cor <- cor(pop_size,life_exp)

perm_cor <- function(perms = 1000, x, y)
{
  corr_mat <- matrix(0,length(perms),1)
  mylist <- rep(list(0,1000))

  for (i in c(1:perms))
  {
    mylist[[i]] <- sample(y, length(y), replace = FALSE)
    
    corr_mat[[i]] = real_cor + cor(x,mylist[[i]])
  }
  
  return(corr_mat)
}

correlation <- as.tibble(perm_cor(x=life_exp,y=pop_size))

props <- as.tibble(quantile(perm_cor(x=pop_size,y=life_exp)))

standard_dev <- sd(perm_cor(x=life_exp,y=pop_size))

summary(correlation)


ggplot(correlation, aes(x=value))+geom_histogram() + labs(x= "correlation", y = "count", title = "correlation between GDP per capita and life expectency")+ geom_vline(xintercept = real_cor, col = "Blue")
```
