---
title: "Lab 11"
author: "Data Me Pls"
date: "April 2, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# The Name Game

# Team stuff (James and Anna will do it this week, next week is Chris and Amanda (good luck on your matrix test))
```{r, eval=FALSE}
install.packages("babynames")
library(babynames)
babynames<- view(babynames)

fnames<- babynames%>%
  filter(sex=="F")

rachel<- fnames%>%
  filter(str_detect(name, "Ra[ey]?ch"))
  group_by(year)%>%
  summarise(sum(n))
  
ariel<-fnames%>%
  filter(str_detect(name, "Ar[iy]+.l"))
  group_by(year)%>%
  summarize(sum(n))
  
fnamescount<- babynames%>%
  filter(sex=="F", year== 1990)%>%
  summarise(sum(str_detect(name, "Ra[ey]?ch") == T))

asnames <-babynames%>%
  filter(str_detect(name, "^A"))%>%
  group_by(year)%>%
  summarize(sum(n))

ggplot()+
  geom_line(ariel, mapping=aes(x=year, y=`sum(n)`))+
  geom_vline(xintercept= 1989, col="blue")+
  geom_line(anames, mapping=aes(x=year, y=`sum(n)`))
```

## Ariel and Rachel
```{r, eval=FALSE}
fnamescount<- babynames%>%
  filter(sex=="F", year== 2017)%>%
  summarise(sum(str_detect(name, "Ar[iy]+.l") == T))

fnamestotal<- fnames%>%
  filter(year== 2017)%>%
  summarise(sum(n))
```
__Versions of Ariel and Rachel:__

Year  |Ariel    |Rachel 
------|---------|---------
1973  |3        |14
1988  |9        |22
1990  |10       |19

__Probability of Ariel and Rachel:__

Year  |Ariel     |Rachel 
------|----------|---------
1973  |3/1458168 |14/1458168
1988  |9/1780268 |22/1780268
1990  |10/1898046|19/1898046
2017  |20/1711811|7/1711811

## _The Littel_ Mermaid Effect
```{r, eval=FALSE}


```

---

## Group Histogram

---

## Chris

## Amanda

## James

## Anna
```{r, eval=FALSE}
myname<- babynames%>%
  filter(str_detect(name, "Anna$"))%>%
  group_by(year)%>%
  summarize(sum(n))

myname<- myname%>%
  rename(Count= `sum(n)`, Year= year)

anames <-babynames%>%
  filter(str_detect(name, "^Ann"))%>%
  group_by(year)%>%
  summarise(sum(n))

anames<- anames%>%
  rename(Count= `sum(n)`, Year= year)

ggplot()+
  geom_line(myname, mapping=aes(x= Year, y= Count, color="Anna"))+
  geom_line(anames, mapping=aes(x= Year, y= Count, color= "'Ann'"))+
  geom_vline(xintercept= 1999, col="Green")+
  labs(title= "Popularity of Anna and 'Ann' Names", color= "Name")
```


# What we did

__Chris:__

__Amanda:__

__James:__

__Anna:__ 